// AUTH types
export const AUTH_USER = "AUTH_USER";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_SIGNOUT = "AUTH_SIGNOUT";

// CART types
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const MOVE_TO_WISHLIST = "MOVE_TO_WISHLIST";
export const REMOVE_ALL_FROM_CART = "REMOVE_ALL_FROM_CART";
export const PLUS_COUNTER_PRODUCT = "PLUS_COUNTER_PRODUCT";
export const MINUS_COUNTER_PRODUCT = "MINUS_COUNTER_PRODUCT";

//ORDER types
export const ORDER_PRODUCTS = "ORDER_PRODUCTS";
export const ORDER_PRODUCTS_LOADING = "ORDER_PRODUCTS_LOADING";
export const ORDER_PRODUCTS_FAILED = "ORDER_PRODUCTS_FAILED";

//RESET types
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_LOADING = "RESET_PASSWORD_LOADING";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";
export const RESET_PASSWORD_CLEAR = "RESET_PASSWORD_CLEAR";

//PERSONALINFO types 
export const PERSONAL_INFO = "PERSONAL_INFO";
export const PERSONAL_INFO_LOADING = "PERSONAL_INFO_LOADING";
export const PERSONAL_INFO_FAILED = "PERSONAL_INFO_FAILED";

//LIKE types
export const LIKE_PRODUCTS = "LIKE_PRODUCTS";
export const REMOVE_LIKED_PRODUCT = "REMOVE_LIKED_PRODUCT";
export const REMOVE_LIKED_PRODUCTS = "REMOVE_LIKED_PRODUCTS";

// CATEGORY types

export const CATEGORY_PRODUCTS = "CATEGORY_PRODUCTS";
export const CATEGORY_PRODUCTS_FAILED = "CATEGORY_PRODUCTS_FAILED";
export const CATEGORY_PRODUCTS_LOADING = "CATEGORY_PRODUCTS_LOADING";